### ISSUE TITLE
Unable to use Metamap API since service ticket call is failing with 400 Bad Request

### ISSUE THREAD

**Issue by anupkawtia** [ziy/skr-webapi#1]
Hi,

We are using MetaMap WebAPI v2_3 (https://ii.nlm.nih.gov/Web_API/index.shtml). We are not able to access the APIs as one of the steps in the Web API flow is not working. We are getting 400 bad request from the getServiceTicket API (https://utslogin.nlm.nih.gov/cas/v1/tickets/TGT-2881-WImAhLaQz67BY0e7gEXbxYDfbReOajSiV2939oxtUngrAuViXM-cas). The credentials provided  are correct. We are getting error saying "Bad service" for the API call.

Below is the metamap service URL being used:
https://ii.nlm.nih.gov/cgi-bin/II/UTS_Required/API_MM_interactive.pl

The same issue is being seen for the below service URL also:
https://ii.nlm.nih.gov/cgi-bin/II/UTS_Required/API_SR_interactive.pl

Can you please help us out in resolving the same.

Thanks.

We also tried in postman through rest client but same error:
1. Make API call to get ticketGrantingTicket:

curl -X POST \
  https://utslogin.nlm.nih.gov/cas/v1/tickets \
  -H 'content-type: application/x-www-form-urlencoded' \
  -d 'username=<username>&password=<password>'
We get grant ticket as expected.

2. Make API call to get serviceTicket:

curl -X POST \
  https://utslogin.nlm.nih.gov/cas/v1/tickets/TGT-5173-NVWM2ya6OdPfYRxy5x7IAGeHcjFIbHUAAonOEfgCxYJTCBu30t-cas \
  -H 'content-type: application/x-www-form-urlencoded' \
  -d service=https%3A%2F%2Fii.nlm.nih.gov%2Fcgi-bin%2FII%2FUTS_Required%2FAPI_MM_interactive.pl

Below error will be seen with HTTP 400 response (removed HTML tags, as ticketing system does not allow):
        bad service name: https://ii.nlm.nih.gov/cgi-bin/II/UTS_Required/API_MM_interactive.pl

**Comment by anupkawtia** [comment]
@ziy Can you please help us resolve the issue.

**Comment by ziy** [comment]
We are not the original developers of the WebAPI. This repository only reorganizes the project structure to mavenize it. I would recommend to contact the owner / author of the WebAPI for this type of error.
